server:
  servlet:
    context-path: /demo #��Ŀ����ǰ׺
spring:
  datasource:
    name: test  #���ݿ���
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  #���ݿ���������
mybatis:
  mapper-locations: classpath:mapper/*.xml  #����ӳ���ļ�